POST http://localhost:8080/engine-rest/message
Content-Type: application/json

{
  "messageName" : "msg_IDVResultaatBeschikbaar",
  "processInstanceId": "56d998d5-9935-11ec-a5e3-0242ac110005",
  "processVariables" : {
    "idvGeldig" : {"value" : true, "type": "Boolean"},
    "herIDVMogelijk": {"value" : false, "type": "Boolean"}
  }
}