POST http://localhost:8080/engine-rest/message
Content-Type: application/json

{
  "messageName" : "msg_IDVResultaatBeschikbaar",
  "correlationKeys" : {
    "relatieNummer" : {"value" : "C123456", "type": "String"}
  },
  "processVariables" : {
    "idvGeldig" : {"value" : true, "type": "Boolean"},
    "herIDVMogelijk": {"value" : false, "type": "Boolean"}
  }
}