version: '3'
services:

  camunda:
    image: edwinw.azurecr.io/camunda-bpm-platform:1.0
    container_name: camunda
    build: ../Camunda
    volumes:
      - camunda:/camunda 
    ports:
      - "8080:8080"   
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/engine-rest/engine"]
      interval: 1s
      timeout: 3s
      retries: 60         

  external-task-dispatcher01:
    image: edwinw.azurecr.io/external-task-dispatcher:1.0
    container_name: cetd01
    build: ../    
    depends_on:
      camunda:
        condition: service_healthy
    env_file:
      - cetd-variables.env

  external-task-dispatcher02:
    image: edwinw.azurecr.io/external-task-dispatcher:1.0
    container_name: cetd02
    build: ../
    depends_on:
      camunda:
        condition: service_healthy
    env_file:
      - cetd-variables.env

volumes:
  camunda:
    external: true
